"""Add Thresholds to LineTraining Forms

Revision ID: 16c51b787c03
Revises: 76634601d5a0
Create Date: 2025-04-30 19:57:23.055712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16c51b787c03'
down_revision = '76634601d5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_training_form', schema=None) as batch_op:
        batch_op.alter_column('threshold_total_sectors',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('threshold_total_hours',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_training_form', schema=None) as batch_op:
        batch_op.alter_column('threshold_total_hours',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('threshold_total_sectors',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
