"""Change unique on Groundhandler

Revision ID: 27f4b0880ebc
Revises: 0f76d7a0cc85
Create Date: 2025-04-09 03:45:03.935066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27f4b0880ebc'
down_revision = '0f76d7a0cc85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ground_handlers', schema=None) as batch_op:
        batch_op.alter_column('additional_contacts',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_index('primary_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ground_handlers', schema=None) as batch_op:
        batch_op.create_index('primary_email', ['primary_email'], unique=True)
        batch_op.alter_column('additional_contacts',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###
