"""Fix CrewAcknowledgement FK types to match Flight and User

Revision ID: 2afbd7cb8a57
Revises: b2dad447a754
Create Date: 2025-04-10 21:09:54.205007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2afbd7cb8a57'
down_revision = 'b2dad447a754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew_acknowledgement', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_constraint('crew_acknowledgement_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['crew_member_id'], ['employee_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew_acknowledgement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('crew_acknowledgement_ibfk_3', 'user', ['crew_member_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
