"""Add completed_offboarding

Revision ID: 35a3d283db08
Revises: 3b0bea9a73ce
Create Date: 2025-04-18 01:12:45.030764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a3d283db08'
down_revision = '3b0bea9a73ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_onboarding', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('completed_offboarding', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('completed_offboarding')
        batch_op.drop_column('completed_onboarding')

    with op.batch_alter_table('hr_task_template', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
