"""Remove assigned_to_email from HRTaskTemplate table

Revision ID: 38ea17a6be4d
Revises: d96eca506d83
Create Date: 2025-04-16 16:10:49.525322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38ea17a6be4d'
down_revision = 'd96eca506d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_task_template', schema=None) as batch_op:
        batch_op.drop_column('assigned_to_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_task_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_email', mysql.VARCHAR(length=150), nullable=True))

    # ### end Alembic commands ###
