"""Add due_date to UserHRTask Table

Revision ID: 3b0bea9a73ce
Revises: b747631741bb
Create Date: 2025-04-17 03:30:23.448119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0bea9a73ce'
down_revision = 'b747631741bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_hr_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_hr_task', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    with op.batch_alter_table('hr_task_template', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
