"""Add visible_headers to CrewCheck

Revision ID: 46539b0e184d
Revises: 5d52f014ba97
Create Date: 2025-04-04 21:47:16.120785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46539b0e184d'
down_revision = '5d52f014ba97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_headers', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew_checks', schema=None) as batch_op:
        batch_op.drop_column('visible_headers')

    # ### end Alembic commands ###
