"""Change crew checks nullable values

Revision ID: 4a72ca5408a9
Revises: 46539b0e184d
Create Date: 2025-04-04 22:21:11.127646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a72ca5408a9'
down_revision = '46539b0e184d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew_check_meta', schema=None) as batch_op:
        batch_op.alter_column('aircraft_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('aircraft_registration',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('type_of_check',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('logbook_sticker_issued',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True)
        batch_op.alter_column('examiner_license_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew_check_meta', schema=None) as batch_op:
        batch_op.alter_column('examiner_license_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('logbook_sticker_issued',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False)
        batch_op.alter_column('type_of_check',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('aircraft_registration',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('aircraft_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
