"""Add Pages Requried to Document Type

Revision ID: 4c7d302834ea
Revises: 71c8ed44d2d4
Create Date: 2025-05-06 04:23:14.733542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7d302834ea'
down_revision = '71c8ed44d2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pages_required', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.drop_column('pages_required')

    # ### end Alembic commands ###
