"""empty message

Revision ID: 5d52f014ba97
Revises: 
Create Date: 2025-03-21 02:09:29.041985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d52f014ba97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index('id')

    with op.batch_alter_table('check_item_grade', schema=None) as batch_op:
        batch_op.alter_column('grader_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('graded_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_grade_meta', type_='foreignkey')
        batch_op.drop_constraint('fk_grade_item', type_='foreignkey')
        batch_op.create_foreign_key(None, 'check_items', ['check_item_id'], ['id'])
        batch_op.create_foreign_key(None, 'crew_check_meta', ['crew_check_meta_id'], ['id'])

    with op.batch_alter_table('check_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', mysql.BIGINT(unsigned=True), nullable=False))
        batch_op.alter_column('grade',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('graded_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('version',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_item_crew_check', type_='foreignkey')
        batch_op.drop_constraint('fk_item_grader', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['grader_id'], ['id'])
        batch_op.create_foreign_key(None, 'crew_checks', ['crew_check_id'], ['id'])
        batch_op.drop_column('order_no')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('passing_mark',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('valid_for_days',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text("'365'"))
        batch_op.alter_column('available_before_expiry_days',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text("'30'"))
        batch_op.drop_index('id')

    with op.batch_alter_table('course_role', schema=None) as batch_op:
        batch_op.drop_constraint('fk_course_role_role', type_='foreignkey')
        batch_op.drop_constraint('fk_course_role_course', type_='foreignkey')
        batch_op.create_foreign_key(None, 'role_type', ['role_id'], ['roleID'])
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    with op.batch_alter_table('crew', schema=None) as batch_op:
        batch_op.alter_column('flightId',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('crewPositionId',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('employeeId',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('dutyStartTime',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('dutyFinishTime',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('id')
        batch_op.create_foreign_key(None, 'user', ['employeeId'], ['id'])
        batch_op.create_foreign_key(None, 'flight', ['flightId'], ['id'])

    with op.batch_alter_table('crew_check_meta', schema=None) as batch_op:
        batch_op.alter_column('flight_time_day',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('flight_time_night',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('flight_time_if',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('template_version',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_meta_candidate', type_='foreignkey')
        batch_op.drop_constraint('fk_meta_crew_check', type_='foreignkey')
        batch_op.create_foreign_key(None, 'crew_checks', ['crew_check_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['candidate_id'], ['id'])

    with op.batch_alter_table('crew_check_role', schema=None) as batch_op:
        batch_op.drop_constraint('fk_crewcheck_role_crew_check', type_='foreignkey')
        batch_op.drop_constraint('fk_crewcheck_role_role', type_='foreignkey')
        batch_op.create_foreign_key(None, 'role_type', ['role_id'], ['roleID'])
        batch_op.create_foreign_key(None, 'crew_checks', ['crew_check_id'], ['id'])

    with op.batch_alter_table('crew_checks', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('id')

    with op.batch_alter_table('email_config', schema=None) as batch_op:
        batch_op.drop_index('id')

    with op.batch_alter_table('employee_skills', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('skill_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('priority',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)
        batch_op.drop_index('id')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_enroll_user', type_='foreignkey')
        batch_op.drop_constraint('fk_enroll_course', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('flightid',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('employee_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('parent_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('flightStatusId',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('flightDate',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('departurePlaceId',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('departureScheduled',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('departureEstimate',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('departureActual',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('departureTakeOff',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('arrivalPlaceId',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('arrivalScheduled',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('arrivalEstimate',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('arrivalLanded',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('arrivalActual',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('divertedPlaceId',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('divertedArrivalTime',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('customerId',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('flightModelId',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('flightLineId',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('flightTypeId',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('flightNumberId',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('flightRegistrationId',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('plannedFlightTime',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('calculatedTakeOffTime',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('abortCancelCodeId',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.drop_index('id')
        batch_op.create_foreign_key(None, 'flight', ['parent_id'], ['id'])

    with op.batch_alter_table('form_template', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('id')

    with op.batch_alter_table('ground_handlers', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_ground_port', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ports', ['port_id'], ['id'])

    with op.batch_alter_table('handler_flight_map', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_hfm_handler', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ground_handlers', ['handler_id'], ['id'])

    with op.batch_alter_table('job_title', schema=None) as batch_op:
        batch_op.alter_column('manager_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('reports_to',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('location_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.drop_index('id')
        batch_op.create_foreign_key(None, 'location', ['location_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['manager_id'], ['id'])
        batch_op.create_foreign_key(None, 'job_title', ['reports_to'], ['id'])

    with op.batch_alter_table('line_training_form', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('id')

    with op.batch_alter_table('line_training_form_role', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ltf_role_role', type_='foreignkey')
        batch_op.drop_constraint('fk_ltf_role_form', type_='foreignkey')
        batch_op.create_foreign_key(None, 'line_training_form', ['line_training_form_id'], ['id'])
        batch_op.create_foreign_key(None, 'role_type', ['role_type_id'], ['roleID'])

    with op.batch_alter_table('line_training_items', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_lti_form', type_='foreignkey')
        batch_op.create_foreign_key(None, 'line_training_form', ['form_id'], ['id'])

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index('id')

    with op.batch_alter_table('payroll_information', schema=None) as batch_op:
        batch_op.alter_column('hours',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_payroll_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('payroll_period', schema=None) as batch_op:
        batch_op.drop_index('id')

    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.drop_index('id')

    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.alter_column('qualification_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('valid_from',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('valid_to',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_qual_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['employee_id'], ['id'])

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_question_course', type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    with op.batch_alter_table('role_type', schema=None) as batch_op:
        batch_op.drop_index('roleID')

    with op.batch_alter_table('roster_changes', schema=None) as batch_op:
        batch_op.alter_column('published_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('acknowledged_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_roster_crew', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['crew_id'], ['id'])

    with op.batch_alter_table('route_permissions', schema=None) as batch_op:
        batch_op.drop_index('id')

    with op.batch_alter_table('route_role', schema=None) as batch_op:
        batch_op.drop_constraint('fk_route_role_role', type_='foreignkey')
        batch_op.drop_constraint('fk_route_role_permission', type_='foreignkey')
        batch_op.create_foreign_key(None, 'route_permissions', ['route_permission_id'], ['id'])
        batch_op.create_foreign_key(None, 'role_type', ['role_type_id'], ['roleID'])

    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.alter_column('takeoff_count',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('landing_count',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('sector_number',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_sector_form', type_='foreignkey')
        batch_op.drop_constraint('fk_sector_note_creator', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_line_training_forms', ['form_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['note_creator_id'], ['id'])

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_task_topic', type_='foreignkey')
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['id'])

    with op.batch_alter_table('task_completion', schema=None) as batch_op:
        batch_op.alter_column('completed_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_tc_trainer', type_='foreignkey')
        batch_op.drop_constraint('fk_tc_task', type_='foreignkey')
        batch_op.drop_constraint('fk_tc_form', type_='foreignkey')
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_line_training_forms', ['form_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['trainer_id'], ['id'])

    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.alter_column('runway_inspections',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('submitted_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_timesheet_period', type_='foreignkey')
        batch_op.drop_constraint('fk_timesheet_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'payroll_period', ['payroll_period_id'], ['id'])

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_topic_template', type_='foreignkey')
        batch_op.drop_constraint('fk_topic_user_form', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_line_training_forms', ['user_line_training_form_id'], ['id'])
        batch_op.create_foreign_key(None, 'line_training_form', ['line_training_form_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('location_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_user_jobtitle', type_='foreignkey')
        batch_op.create_foreign_key(None, 'job_title', ['job_title_id'], ['id'])
        batch_op.create_foreign_key(None, 'location', ['location_id'], ['id'])

    with op.batch_alter_table('user_answers', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_useranswer_answer', type_='foreignkey')
        batch_op.drop_constraint('fk_useranswer_attempt', type_='foreignkey')
        batch_op.drop_constraint('fk_useranswer_question', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_exam_attempts', ['attempt_id'], ['id'])
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'])
        batch_op.create_foreign_key(None, 'answers', ['answer_id'], ['id'])

    with op.batch_alter_table('user_exam_attempts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('expiry_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_attempt_course', type_='foreignkey')
        batch_op.drop_constraint('fk_attempt_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user_line_training_forms', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('total_sectors',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_ultf_user', type_='foreignkey')
        batch_op.drop_constraint('fk_ultf_template', type_='foreignkey')
        batch_op.create_foreign_key(None, 'line_training_form', ['template_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_constraint('user_role_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('user_role_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'role_type', ['role_type_id'], ['roleID'])

    with op.batch_alter_table('user_slide_progress', schema=None) as batch_op:
        batch_op.alter_column('last_slide_viewed',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('expiry_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('id')
        batch_op.drop_constraint('fk_progress_course', type_='foreignkey')
        batch_op.drop_constraint('fk_progress_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_slide_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_progress_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_progress_course', 'course', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('expiry_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('last_slide_viewed',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_role_ibfk_1', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('user_role_ibfk_2', 'role_type', ['role_type_id'], ['roleID'], ondelete='CASCADE')

    with op.batch_alter_table('user_line_training_forms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_ultf_template', 'line_training_form', ['template_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_ultf_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('total_sectors',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('user_exam_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_attempt_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_attempt_course', 'course', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('expiry_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('user_answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_useranswer_question', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_useranswer_attempt', 'user_exam_attempts', ['attempt_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_useranswer_answer', 'answers', ['answer_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_user_jobtitle', 'job_title', ['job_title_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('location_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('employee_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_topic_user_form', 'user_line_training_forms', ['user_line_training_form_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_topic_template', 'line_training_form', ['line_training_form_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_timesheet_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_timesheet_period', 'payroll_period', ['payroll_period_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('submitted_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('runway_inspections',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('task_completion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_tc_form', 'user_line_training_forms', ['form_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_tc_task', 'task', ['task_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_tc_trainer', 'user', ['trainer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_task_topic', 'topic', ['topic_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_sector_note_creator', 'user', ['note_creator_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_sector_form', 'user_line_training_forms', ['form_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('sector_number',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('landing_count',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('takeoff_count',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('route_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_route_role_permission', 'route_permissions', ['route_permission_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_route_role_role', 'role_type', ['role_type_id'], ['roleID'], ondelete='CASCADE')

    with op.batch_alter_table('route_permissions', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('roster_changes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_roster_crew', 'user', ['crew_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('acknowledged_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('published_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('role_type', schema=None) as batch_op:
        batch_op.create_index('roleID', ['roleID'], unique=True)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_question_course', 'course', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_qual_user', 'user', ['employee_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('valid_to',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('valid_from',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('qualification_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('payroll_period', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('payroll_information', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_payroll_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('hours',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('line_training_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_lti_form', 'line_training_form', ['form_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('line_training_form_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_ltf_role_form', 'line_training_form', ['line_training_form_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_ltf_role_role', 'role_type', ['role_type_id'], ['roleID'], ondelete='CASCADE')

    with op.batch_alter_table('line_training_form', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('job_title', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('location_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('reports_to',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('manager_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('handler_flight_map', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_hfm_handler', 'ground_handlers', ['handler_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('ground_handlers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_ground_port', 'ports', ['port_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('form_template', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('abortCancelCodeId',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calculatedTakeOffTime',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('plannedFlightTime',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('flightRegistrationId',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('flightNumberId',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('flightTypeId',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('flightLineId',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('flightModelId',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('customerId',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('divertedArrivalTime',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('divertedPlaceId',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('arrivalActual',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('arrivalLanded',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('arrivalEstimate',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('arrivalScheduled',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('arrivalPlaceId',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('departureTakeOff',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('departureActual',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('departureEstimate',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('departureScheduled',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('departurePlaceId',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('flightDate',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('flightStatusId',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('parent_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('employee_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('flightid',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_enroll_course', 'course', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_enroll_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('employee_skills', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('priority',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('skill_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('employee_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('email_config', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('crew_checks', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('crew_check_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_crewcheck_role_role', 'role_type', ['role_id'], ['roleID'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_crewcheck_role_crew_check', 'crew_checks', ['crew_check_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('crew_check_meta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_meta_crew_check', 'crew_checks', ['crew_check_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_meta_candidate', 'user', ['candidate_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('template_version',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('flight_time_if',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('flight_time_night',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('flight_time_day',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('crew', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('dutyFinishTime',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('dutyStartTime',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('employeeId',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('crewPositionId',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('flightId',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('course_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_course_role_course', 'course', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_course_role_role', 'role_type', ['role_id'], ['roleID'], ondelete='CASCADE')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('available_before_expiry_days',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'30'"))
        batch_op.alter_column('valid_for_days',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'365'"))
        batch_op.alter_column('passing_mark',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('check_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_no', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_item_grader', 'user', ['grader_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_item_crew_check', 'crew_checks', ['crew_check_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('version',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('graded_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('grade',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('order')

    with op.batch_alter_table('check_item_grade', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_grade_item', 'check_items', ['check_item_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_grade_meta', 'crew_check_meta', ['crew_check_meta_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('graded_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('grader_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    # ### end Alembic commands ###
