"""empty message

Revision ID: 65262f8bdab3
Revises: 16c51b787c03
Create Date: 2025-05-01 19:14:13.573973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65262f8bdab3'
down_revision = '16c51b787c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('line_training_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threshold_total_sectors', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('threshold_total_hours', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)

    with op.batch_alter_table('line_training_form', schema=None) as batch_op:
        batch_op.drop_column('threshold_total_hours')
        batch_op.drop_column('threshold_total_sectors')

    with op.batch_alter_table('crew_checks', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
