"""Add Document Type Relationship to HRTaskTemplate

Revision ID: 71c8ed44d2d4
Revises: af98c0e6a7dc
Create Date: 2025-05-05 23:40:18.288625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c8ed44d2d4'
down_revision = 'af98c0e6a7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_task_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'document_types', ['document_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_task_template', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('document_type_id')

    # ### end Alembic commands ###
