"""Add Soft Delete to CrewCheck

Revision ID: 74d94ae9d07a
Revises: b9c4e1458af3
Create Date: 2025-04-30 18:46:31.749532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d94ae9d07a'
down_revision = 'b9c4e1458af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew_checks', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
