"""Add Thresholds to LineTraining Forms

Revision ID: 76634601d5a0
Revises: 74d94ae9d07a
Create Date: 2025-04-30 19:51:38.070124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76634601d5a0'
down_revision = '74d94ae9d07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_training_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threshold_total_sectors', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('threshold_total_hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_training_form', schema=None) as batch_op:
        batch_op.drop_column('threshold_total_hours')
        batch_op.drop_column('threshold_total_sectors')

    # ### end Alembic commands ###
