"""Adding Recruitment Type Table

Revision ID: 78d8029dd8ef
Revises: 8334ae8e4a22
Create Date: 2025-04-16 17:05:52.351362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d8029dd8ef'
down_revision = '8334ae8e4a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruitment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recruitment_type')
    # ### end Alembic commands ###
