"""Add Job Titles to Navbar

Revision ID: 79c56e5d70bc
Revises: 4c7d302834ea
Create Date: 2025-05-19 19:18:21.010442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79c56e5d70bc'
down_revision = '4c7d302834ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nav_item_permission', schema=None) as batch_op:
        batch_op.alter_column('job_title_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'job_title', ['job_title_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nav_item_permission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('job_title_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
