"""Add days_before to HRTaskTemplate

Revision ID: 7c11fb1c5c91
Revises: db4d906adcbb
Create Date: 2025-04-17 02:46:06.537336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c11fb1c5c91'
down_revision = 'db4d906adcbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_task_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_before', sa.Integer(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_task_template', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('days_before')

    # ### end Alembic commands ###
