"""Adding RecruitmentRequest

Revision ID: 8334ae8e4a22
Revises: 38ea17a6be4d
Create Date: 2025-04-16 16:44:31.822215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8334ae8e4a22'
down_revision = '38ea17a6be4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruitment_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hiring_manager_name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('location_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('job_title_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('number_of_positions', sa.Integer(), nullable=True),
    sa.Column('employment_type_id', sa.Integer(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('has_position_description', sa.Boolean(), nullable=True),
    sa.Column('remuneration_range', sa.String(length=100), nullable=True),
    sa.Column('submitted_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['employment_type_id'], ['employment_type.id'], ),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_title.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recruitment_request')
    # ### end Alembic commands ###
