"""Add DocumentType table and FK to DocumentReviewRequest

Revision ID: 8800d5da23a1
Revises: f3a9985ec6e1
Create Date: 2025-04-13 20:17:38.221565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8800d5da23a1'
down_revision = 'f3a9985ec6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('document_review_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('document_expiry_date', sa.Date(), nullable=False))
        batch_op.create_foreign_key(None, 'document_types', ['document_type_id'], ['id'])
        batch_op.drop_column('document_date')
        batch_op.drop_column('document_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_review_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('document_date', sa.DATE(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('document_expiry_date')
        batch_op.drop_column('document_type_id')

    op.drop_table('document_types')
    # ### end Alembic commands ###
