"""Change medical_expiry_days to string

Revision ID: 91c94389bfbf
Revises: ea42cce9dd4d
Create Date: 2025-04-13 19:38:58.364217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91c94389bfbf'
down_revision = 'ea42cce9dd4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_config', schema=None) as batch_op:
        batch_op.alter_column('medical_expiry_days',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_config', schema=None) as batch_op:
        batch_op.alter_column('medical_expiry_days',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
