"""Enhance HRTaskTemplate with multiple job titles and manager link

Revision ID: 9922788cd0bd
Revises: 78d8029dd8ef
Create Date: 2025-04-16 22:27:43.314218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9922788cd0bd'
down_revision = '78d8029dd8ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_task_template_job_title',
    sa.Column('task_template_id', sa.Integer(), nullable=False),
    sa.Column('job_title_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_title.id'], ),
    sa.ForeignKeyConstraint(['task_template_id'], ['hr_task_template.id'], ),
    sa.PrimaryKeyConstraint('task_template_id', 'job_title_id')
    )
    with op.batch_alter_table('hr_task_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsible_manager_id', mysql.BIGINT(unsigned=True), nullable=True))
        batch_op.add_column(sa.Column('responsible_email', sa.String(length=150), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.drop_constraint('hr_task_template_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['responsible_manager_id'], ['id'])
        batch_op.drop_column('job_title_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_task_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('hr_task_template_ibfk_1', 'job_title', ['job_title_id'], ['id'])
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('responsible_email')
        batch_op.drop_column('responsible_manager_id')

    op.drop_table('hr_task_template_job_title')
    # ### end Alembic commands ###
