"""Fix datatype mismatch in CrewAcknowledgement

Revision ID: 9cce8d02f87a
Revises: 27f4b0880ebc
Create Date: 2025-04-10 20:51:06.736493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cce8d02f87a'
down_revision = '27f4b0880ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crew_acknowledgement',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('flight_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('crew_member_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crew_member_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crew_acknowledgement')
    # ### end Alembic commands ###
