"""empty message

Revision ID: af98c0e6a7dc
Revises: 65262f8bdab3
Create Date: 2025-05-05 23:05:54.978945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af98c0e6a7dc'
down_revision = '65262f8bdab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_task_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_employee_task', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_task_template', schema=None) as batch_op:
        batch_op.drop_column('is_employee_task')

    # ### end Alembic commands ###
