"""Add timing to HRTaskTemplate Table

Revision ID: b747631741bb
Revises: 7c11fb1c5c91
Create Date: 2025-04-17 03:11:51.942633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b747631741bb'
down_revision = '7c11fb1c5c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_task_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timing', sa.String(length=20), nullable=False))
        #batch_op.create_foreign_key(None, 'job_title', ['responsible_job_title_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_task_template', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('timing')

    # ### end Alembic commands ###
