"""Fix datatype for navbar permission

Revision ID: c44e3388f270
Revises: 4f8e0cf4a183
Create Date: 2025-04-08 06:05:43.453109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c44e3388f270'
down_revision = '4f8e0cf4a183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nav_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.alter_column('endpoint',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key(None, 'nav_item', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nav_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('endpoint',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
