"""Add inherit_roles to NavItem

Revision ID: c5e84e70e5bf
Revises: 2afbd7cb8a57
Create Date: 2025-04-12 16:16:57.832034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e84e70e5bf'
down_revision = '2afbd7cb8a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nav_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inherit_roles', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nav_item', schema=None) as batch_op:
        batch_op.drop_column('inherit_roles')

    # ### end Alembic commands ###
