"""Add completed_offboarding

Revision ID: cee8665bb628
Revises: 35a3d283db08
Create Date: 2025-04-20 20:59:18.141887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cee8665bb628'
down_revision = '35a3d283db08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('recruitment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('document_review_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('reviewed_by_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('document_expiry_date', sa.Date(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_task_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsible_job_title_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('days_before', sa.Integer(), nullable=True),
    sa.Column('timing', sa.String(length=20), nullable=False),
    sa.Column('responsible_manager_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('responsible_email', sa.String(length=150), nullable=True),
    sa.Column('phase', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['responsible_job_title_id'], ['job_title.id'], ),
    sa.ForeignKeyConstraint(['responsible_manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruitment_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hiring_manager_name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('location_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('job_title_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('number_of_positions', sa.Integer(), nullable=True),
    sa.Column('employment_type_id', sa.Integer(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('has_position_description', sa.Boolean(), nullable=True),
    sa.Column('remuneration_range', sa.String(length=100), nullable=True),
    sa.Column('submitted_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['employment_type_id'], ['employment_type.id'], ),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_title.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_task_template_job_title',
    sa.Column('task_template_id', sa.Integer(), nullable=False),
    sa.Column('job_title_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_title.id'], ),
    sa.ForeignKeyConstraint(['task_template_id'], ['hr_task_template.id'], ),
    sa.PrimaryKeyConstraint('task_template_id', 'job_title_id')
    )
    op.create_table('user_hr_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('task_template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('completed_by', sa.String(length=150), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_template_id'], ['hr_task_template.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_expiry_days', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('medical_expiry_email', sa.String(length=255), nullable=True))

    with op.batch_alter_table('nav_item', schema=None) as batch_op:
        batch_op.drop_constraint('nav_item_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'nav_item', ['parent_id'], ['id'])

    with op.batch_alter_table('payroll_information', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.drop_constraint('timesheet_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint('topic_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_line_training_forms', ['user_line_training_form_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('offboarding_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('completed_onboarding', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('completed_offboarding', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user_line_training_forms', schema=None) as batch_op:
        batch_op.drop_constraint('user_line_training_forms_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_line_training_forms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_line_training_forms_ibfk_2', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('completed_offboarding')
        batch_op.drop_column('completed_onboarding')
        batch_op.drop_column('offboarding_end_date')
        batch_op.drop_column('onboarding_start_date')

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('topic_ibfk_1', 'user_line_training_forms', ['user_line_training_form_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('timesheet_ibfk_1', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payroll_information', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('nav_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('nav_item_ibfk_1', 'nav_item', ['parent_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('email_config', schema=None) as batch_op:
        batch_op.drop_column('medical_expiry_email')
        batch_op.drop_column('medical_expiry_days')

    op.drop_table('user_hr_task')
    op.drop_table('hr_task_template_job_title')
    op.drop_table('recruitment_request')
    op.drop_table('hr_task_template')
    op.drop_table('document_review_requests')
    op.drop_table('recruitment_type')
    op.drop_table('employment_type')
    op.drop_table('document_types')
    op.drop_table('department')
    # ### end Alembic commands ###
