"""Adding HR Moduel

Revision ID: d96eca506d83
Revises: 8800d5da23a1
Create Date: 2025-04-16 15:39:39.805818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd96eca506d83'
down_revision = '8800d5da23a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_task_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_title_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('phase', sa.String(length=20), nullable=True),
    sa.Column('assigned_to_email', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_title.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_hr_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('task_template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('completed_by', sa.String(length=150), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_template_id'], ['hr_task_template.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_hr_task')
    op.drop_table('hr_task_template')
    # ### end Alembic commands ###
