"""Add start and finish dates to the User table

Revision ID: db4d906adcbb
Revises: c68b37def332
Create Date: 2025-04-17 00:33:45.919413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4d906adcbb'
down_revision = 'c68b37def332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('offboarding_end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('offboarding_end_date')
        batch_op.drop_column('onboarding_start_date')

    with op.batch_alter_table('hr_task_template', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
