"""Add medical expiry config fields

Revision ID: ea42cce9dd4d
Revises: c5e84e70e5bf
Create Date: 2025-04-13 19:30:58.831669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea42cce9dd4d'
down_revision = 'c5e84e70e5bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_expiry_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('medical_expiry_email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_config', schema=None) as batch_op:
        batch_op.drop_column('medical_expiry_email')
        batch_op.drop_column('medical_expiry_days')

    # ### end Alembic commands ###
