import os

DEBUG = True
SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = os.getenv('SECRET_KEY')
SESSION_COOKIE_SECURE = False
REMEMBER_COOKIE_SECURE = False
CURRENT_TEMPLATE_VERSION = 2

MAIL_SERVER = 'send.xtra.co.nz'
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_USERNAME = os.getenv('MAIL_USERNAME')
MAIL_PASSWORD = os.getenv('MAIL_PASSWORD')
MAIL_DEFAULT_SENDER = os.getenv('MAIL_DEFAULT_SENDER')

BASE_URL = 'http://127.0.0.1:5000/'
